{"errorMessage": "Unknown option ssl_cert_reqs", "errorType": "ConfigurationError", "requestId": "f788025c-98af-46a7-add7-8aacb99826d9", "stackTrace": ["  File \"/var/task/lambda_coletor.py\", line 342, in lambda_handler\n    stats = collector.collect_all_news()\n", "  File \"/var/task/lambda_coletor.py\", line 285, in collect_all_news\n    client, collection = get_collection(\"noticias_coletadas\")\n", "  File \"/var/task/utils.py\", line 245, in get_collection\n    client, db = conectar_mongodb()\n", "  File \"/var/task/utils.py\", line 63, in conectar_mongodb\n    client = MongoClient(\n", "  File \"/var/task/pymongo/mongo_client.py\", line 806, in __init__\n    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())\n", "  File \"/var/task/pymongo/mongo_client.py\", line 806, in <genexpr>\n    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())\n", "  File \"/var/task/pymongo/common.py\", line 821, in validate\n    value = validator(option, value)\n", "  File \"/var/task/pymongo/common.py\", line 167, in raise_config_error\n    raise ConfigurationError(f\"Unknown option {key}\")\n"]}